moved some default apps to optional folder

diff --git a/defaults/bash/functions b/defaults/bash/functions
--- a/defaults/bash/functions
+++ b/defaults/bash/functions
@@ -23,57 +23,60 @@ iso2sd() {
 }
 
 # Create a desktop launcher for a web app
-web2app() {
-  if [ "$#" -ne 3 ]; then
-    echo "Usage: web2app <AppName> <AppURL> <IconURL> (IconURL must be in PNG -- use https://dashboardicons.com)"
-    return 1
-  fi
 
-  local APP_NAME="$1"
-  local APP_URL="$2"
-  local ICON_URL="$3"
-  local ICON_DIR="$HOME/.local/share/applications/icons"
-  local DESKTOP_FILE="$HOME/.local/share/applications/${APP_NAME}.desktop"
-  local ICON_PATH="${ICON_DIR}/${APP_NAME}.png"
+# disabling web2app and web2app-delete functions due to it being tied to chrome which is no longer installed by default 
 
-  mkdir -p "$ICON_DIR"
+# web2app() {
+#   if [ "$#" -ne 3 ]; then
+#     echo "Usage: web2app <AppName> <AppURL> <IconURL> (IconURL must be in PNG -- use https://dashboardicons.com)"
+#     return 1
+#   fi
 
-  if ! curl -sL -o "$ICON_PATH" "$ICON_URL"; then
-    echo "Error: Failed to download icon."
-    return 1
-  fi
+#   local APP_NAME="$1"
+#   local APP_URL="$2"
+#   local ICON_URL="$3"
+#   local ICON_DIR="$HOME/.local/share/applications/icons"
+#   local DESKTOP_FILE="$HOME/.local/share/applications/${APP_NAME}.desktop"
+#   local ICON_PATH="${ICON_DIR}/${APP_NAME}.png"
 
-  cat > "$DESKTOP_FILE" <<EOF
-[Desktop Entry]
-Version=1.0
-Name=$APP_NAME
-Comment=$APP_NAME
-Exec=google-chrome --app="$APP_URL" --name="$APP_NAME" --class="$APP_NAME" --window-size=800,600
-Terminal=false
-Type=Application
-Icon=$ICON_PATH
-Categories=GTK;
-MimeType=text/html;text/xml;application/xhtml_xml;
-StartupNotify=true
-EOF
+#   mkdir -p "$ICON_DIR"
 
-  chmod +x "$DESKTOP_FILE"
-}
+#   if ! curl -sL -o "$ICON_PATH" "$ICON_URL"; then
+#     echo "Error: Failed to download icon."
+#     return 1
+#   fi
 
-web2app-remove() {
-  if [ "$#" -ne 1 ]; then
-    echo "Usage: web2app-remove <AppName>"
-    return 1
-  fi
+#   cat > "$DESKTOP_FILE" <<EOF
+# [Desktop Entry]
+# Version=1.0
+# Name=$APP_NAME
+# Comment=$APP_NAME
+# Exec=google-chrome --app="$APP_URL" --name="$APP_NAME" --class="$APP_NAME" --window-size=800,600
+# Terminal=false
+# Type=Application
+# Icon=$ICON_PATH
+# Categories=GTK;
+# MimeType=text/html;text/xml;application/xhtml_xml;
+# StartupNotify=true
+# EOF
 
-  local APP_NAME="$1"
-  local ICON_DIR="$HOME/.local/share/applications/icons"
-  local DESKTOP_FILE="$HOME/.local/share/applications/${APP_NAME}.desktop"
-  local ICON_PATH="${ICON_DIR}/${APP_NAME}.png"
+#   chmod +x "$DESKTOP_FILE"
+# }
 
-  rm "$DESKTOP_FILE"
-  rm "$ICON_PATH"
-}
+# web2app-remove() {
+#   if [ "$#" -ne 1 ]; then
+#     echo "Usage: web2app-remove <AppName>"
+#     return 1
+#   fi
+
+#   local APP_NAME="$1"
+#   local ICON_DIR="$HOME/.local/share/applications/icons"
+#   local DESKTOP_FILE="$HOME/.local/share/applications/${APP_NAME}.desktop"
+#   local ICON_PATH="${ICON_DIR}/${APP_NAME}.png"
+
+#   rm "$DESKTOP_FILE"
+#   rm "$ICON_PATH"
+# }
 
 # Move a reference to a .desktop file, like Spotify.desktop, to a named folder, like Xtra.
 # Don't use full path for the .desktop file.
